-- What is the total revenue generated by male vs. female customers?

SELECT 
    gender, SUM(purchase_amount) AS revenue
FROM
    customer_data
GROUP BY gender

-- Which customers used a discount but still spent more than the average purchase amount?

SELECT 
    customer_id, purchase_amount
FROM
    customer_data
WHERE
    discount_applied = 'Yes'
        AND purchase_amount >= (SELECT 
            AVG(purchase_amount)
        FROM
            customer_data)
		
-- 3. Which are the top 5 products with the highest average review rating?

SELECT 
    item_purchased,
    AVG(review_rating) AS ' Average review rating'
FROM
    customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- 4. Compare the average purchase amount between standard and express shipping.

SELECT 
    shipping_type, AVG(purchase_amount)
FROM
    customer_data
WHERE
    shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type

-- Do subscribed customers spend more? compare average spend and total revenue
-- between subscribers and non-subscribers.

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer_data 
group by subscription_status
order by total_revenue, avg_spend desc;

-- Which 5 products have the highest percentage of purchases with discount applied?

SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE
                WHEN discount_applied = 'yes' THEN 1
                ELSE 0
            END) / COUNT(*),
            2) AS discount_rate
FROM
    customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- segment customer into new, returning,  and loyal based on their total 
-- number of previous purhases, and show the count each segment.

with customer_type as (
select customer_id, previous_purchases, 
case 
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'loyal'
end as customer_segment 
from customer_data 
)

SELECT 
    customer_segment, COUNT(*) AS 'Number of customers'
FROM
    customer_type
GROUP BY customer_segment

-- 8. what are the top 3 most purchased products within each category ?

with item_counts as (
select category, 
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer_data
group by category, item_purchased
)
select category, item_rank, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- ARE customers who are repeate buyers (more than 5 previous purchases) also likely to subscribers?

SELECT 
    subscription_status, COUNT(customer_id) AS repeat_buyers
FROM
    customer_data
WHERE
    previous_purchases > 5
GROUP BY subscription_status

-- 10. what is the revenue contribution of each age group?
SELECT 
    age_group, SUM(purchase_amount) AS total_revenue
FROM
    customer_data
GROUP BY age_group
ORDER BY total_revenue DESC;

ALTER USER 'root'@'localhost'
IDENTIFIED WITH mysql_native_password
BY 'password';

FLUSH PRIVILEGES;

